# CreeperHeal2

# Delay before a hole is fixed in seconds
initial-delay: 45

# Delay between individual block replacements in ticks
# Zero makes it replace everything at once
between-blocks-delay: 20

# Types of explosions to handle
types:
  creeper: true
  tnt: false
  ghast: false
  wither: false
  minecart-tnt: false
  ender-crystal: false
  bed: false

# Turbo mode can help repair larger explosions faster.
# The minimum number of blocks an explosion should involve before turbo mode is activated
# 0 disabled turbo, I recommend ~5000 if you do enable
turbo-threshold: 0
# The number of blocks to replace in each replacement cycle (For reference, non-turbo is 1)
# Raising this will slighly increase TPS impact
turbo-amount: 3

# Enable stats/usage data collection
bstats: true

# Allow the chaining of TNT explosions rather than just saving the TNT block
explode-tnt: true

# Enable debug mode
debug: false