name: CreeperHeal2
main: net.pdevita.creeperheal2.CreeperHeal2
version: 2.0.1a
api-version: 1.13
author: pmdevita
softdepend:
  - Movecraft
  - Factions

commands:
  creeperheal:
    description: CreeperHeal2 commands
    usage: /creeperheal <command>