name: CreeperHeal2
main: net.pdevita.creeperheal2.CreeperHeal2
version: 1.5.0
api-version: 1.13
author: pmdevita
softdepend:
  - Movecraft

commands:
  creeperheal:
    description: CreeperHeal2 commands
    usage: /creeperheal <command>